### ISSUE TITLE
root element, meta element

### ISSUE THREAD

**Issue by skeys** [IAU-ADES/xsd#11]
An XML document must have a single "root element" that contains all other elements.  For MPC submissions, this is pretty clearly `observationBatch` but I wasn't sure if that made sense for other (non-submission) uses.  I had been thinking maybe just `observations` could serve as a root element in cases where there was no submission header.  But my recent [proposal](https://github.com/IAU-ADES/xsd/issues/4#issuecomment-139043473) on versioning would need a place for schema information.  Mixed in with the observations doesn't seem best.  A separate root element would be better.  Maybe all ADES XML files should have the same root element.  We could just say this is `observationBatch` so a non-submission might look like

```
<observationBatch>
  <xsd-1.0>
    ...
  </xsd-1.0>
  <observations>
    ...
  </observations>
</observationBatch>
```

Or we use a `meta` tag like HTML to contain things such as schema information:

```
<observationBatch>
  <meta>
    <xsd-1.0>
      ...
    </xsd-1.0>
  </meta>
  <observations>
    ...
  </observations>
</observationBatch>
```

I don't have strong feelings either way about a meta tag.

Finally, are we happy with "observationBatch" as a root element?  How about simply "ades"?

**Comment by schastel** [comment]
> Finally, are we happy with "observationBatch" as a root element? How
> about simply "ades"?
> 
> "observationBatch" would make more sense. "ades" does not correspond to the
> document contents: the  document does not contain a standard but
> information that complies to it. Metonymy is acceptable still but may
> introduce confusion.

Since there are apparently at the moment:
- observations, made by the community, sent to the mpc (up to it to accept
  or reject them);
- observations sent by the mpc (accepted) to the community;
- ephemerides/reductions made by the community.

I would suggest 3 acceptable roots identifying the contents.
- observationBatch
- disseminationBatch
- reductionBatch
  The contents of each will be different. Let's take OBS_ID for instance.
  Since it is assigned by the MPC, it must not be in observationBatch and
  must be in disseminationBatch.

**Comment by skeys** [comment]
abandoned
