### ISSUE TITLE
optical and/or radar observations

### ISSUE THREAD

**Issue by schastel** [IAU-ADES/xsd#6]
Is it possible to have for a given observation context, mixed optical and radar observations (referring to that context)? e.g.:

``` <context/>
<observations>
  <optical/>
  <optical/>
  <radar/>
</observations>
```

**Comment by skeys** [comment]
In an MPC submission with an observation context, it doesn't make sense because for example the context specifies a single telescope.  Otherwise, as a bare observation list, it's fine and might be used for example by an orbit computer.

So I think submit.xsd should be changed but the definition of observations in example.xsd should be left allowing the mix.

**Comment by skeys** [comment]
addressed with https://github.com/IAU-ADES/xsd/commit/02422926ded8a82f9c639f7a9afe7da6172e5a2d
